(function(g){'use strict';
const PROFILES={
'ウメ':{ever:false,stems:1,branches:5,leaves:16,wide:1.15,flat:.8,leaf:'deciduous',flower:'flowerPink'},
'イチジク':{ever:false,stems:3,branches:4,leaves:15,wide:1.35,flat:.7,leaf:'fig',fruit:'fruitPurple',fruitSeason:['summer','autumn']},
'ブルーベリー':{ever:false,stems:6,branches:3,leaves:24,wide:1,flat:.9,leaf:'blueberry',flower:'flowerWhite',fruit:'fruitBlue',fruitSeason:['summer']},
'ユズ':{ever:true,stems:1,branches:5,leaves:27,wide:1.05,flat:.95,leaf:'citrus',fruit:'fruitYellow',fruitSeason:['autumn','winter']},
'キンカン':{ever:true,stems:1,branches:4,leaves:30,wide:.72,flat:1.2,leaf:'citrus',fruit:'fruitOrange',fruitSeason:['autumn','winter']},
'甘夏':{ever:true,stems:1,branches:6,leaves:34,wide:1.2,flat:1,leaf:'citrus',fruit:'fruitOrange',fruitSeason:['summer','autumn']},
'カキ':{ever:false,stems:1,branches:6,leaves:20,wide:1.2,flat:.85,leaf:'deciduous',fruit:'fruitOrange',fruitSeason:['autumn','winter']},
'ジューンベリー':{ever:false,stems:4,branches:4,leaves:18,wide:.78,flat:1.25,leaf:'deciduous',flower:'flowerWhite',fruit:'fruitRed',fruitSeason:['summer']},
'ヤマボウシ':{ever:false,stems:1,branches:6,leaves:22,wide:1.25,flat:.48,leaf:'deciduous',flower:'flowerWhite',fruit:'fruitRed',fruitSeason:['autumn']}};
function rnd(seed){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function branch(group,a,b,r,mat){const d=b.clone().sub(a),mesh=new THREE.Mesh(new THREE.CylinderGeometry(r*.55,r,d.length(),6),mat);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.clone().normalize());mesh.castShadow=true;group.add(mesh)}
function leafMaterial(p,state,M){if(state.season==='autumn'&&!p.ever)return p===PROFILES['カキ']||p===PROFILES['ヤマボウシ']?M.autumn:M.autumnGold;if(state.season==='spring')return M.spring;if(state.season==='winter'&&!p.ever)return M.winter;return M[p.leaf]}
g.createPlantModel=function(t,index,state,M,tag){const p=PROFILES[t.name],group=new THREE.Group(),r=rnd(900+index*73),growth=.58+Math.min(10,state.growthYear)*.065,baseH=Math.max(.65,t.h*growth),crown=t.r*growth;const shadow=new THREE.Mesh(new THREE.CircleGeometry(crown*.65,16),M.shadow);shadow.rotation.x=-Math.PI/2;shadow.position.y=.012;group.add(shadow);if(state.mode==='plan'){branch(group,new THREE.Vector3(0,0,0),new THREE.Vector3(0,baseH,0),.07,M.trunk);const crownMesh=new THREE.Mesh(new THREE.CylinderGeometry(crown,crown,.12,16),p.ever?M.planEvergreen:M.planDeciduous);crownMesh.position.y=.12;crownMesh.receiveShadow=true;group.add(crownMesh);group.position.set(t.x,0,t.z);tag(group,{title:t.name,body:`PLAN｜${p.ever?'常緑樹':'落葉樹'}`,meta:[['固定座標',`x ${t.x} / z ${t.z}`],['基準樹高',`${t.h}m`],['基準樹冠半径',`${t.r}m`]]});return group}
for(let s=0;s<p.stems;s++){const x=(s-(p.stems-1)/2)*.08,z=(r()-.5)*.1;branch(group,new THREE.Vector3(x,0,z),new THREE.Vector3(x+(r()-.5)*.12,baseH*.65,z+(r()-.5)*.12),(.07+(t.bush?.018:.045))*growth,M.trunk)}
const tips=[];for(let i=0;i<Math.max(3,Math.round(p.branches*(.65+state.growthYear*.05)));i++){const a=i/p.branches*Math.PI*2+r()*.5,y=baseH*(.42+r()*.24),start=new THREE.Vector3((r()-.5)*.12,y*.72,(r()-.5)*.12),tip=new THREE.Vector3(Math.cos(a)*crown*p.wide*(.45+r()*.35),baseH+(r()-.35)*crown*p.flat,Math.sin(a)*crown*(.45+r()*.35));branch(group,start,tip,.045*growth,M.twig);tips.push(tip)}
let leafCount=Math.round(p.leaves*(.55+state.growthYear*.045));if(state.season==='spring')leafCount*=.72;if(state.season==='winter')leafCount*=p.ever?1:(t.name==='ブルーベリー'?.22:.08);leafCount=Math.min(45,Math.round(leafCount));const lm=leafMaterial(p,state,M),lg=new THREE.IcosahedronGeometry(.18,0);for(let i=0;i<leafCount;i++){const tip=tips[i%tips.length],mesh=new THREE.Mesh(lg,lm);mesh.position.copy(tip).add(new THREE.Vector3((r()-.5)*crown*.65,(r()-.5)*crown*.38,(r()-.5)*crown*.65));mesh.scale.set((t.name==='イチジク'?1.65:.8+r()*.5)*crown*.55,(.28+r()*.22)*crown*.55,(.7+r()*.45)*crown*.55);mesh.rotation.y=r()*Math.PI;mesh.castShadow=i<10;group.add(mesh)}
const sphere=new THREE.SphereGeometry(.075,6,5);if(state.showFlowers&&state.season==='spring'&&p.flower){const count=Math.min(18,6+state.growthYear);for(let i=0;i<count;i++){const q=tips[i%tips.length],f=new THREE.Mesh(sphere,M[p.flower]);f.position.copy(q).add(new THREE.Vector3((r()-.5)*.18,(r()-.5)*.12,(r()-.5)*.18));f.scale.setScalar(t.name==='ヤマボウシ'?1.45:t.name==='ブルーベリー'?.65:1);group.add(f)}}if(state.showFruit&&p.fruit&&p.fruitSeason.includes(state.season)){const sizes={'キンカン':.7,'甘夏':1.55,'ユズ':1.2,'イチジク':1.05,'ブルーベリー':.55,'カキ':1.3,'ジューンベリー':.5,'ヤマボウシ':.75},count=Math.min(16,4+state.growthYear);for(let i=0;i<count;i++){const q=tips[i%tips.length],f=new THREE.Mesh(sphere,M[p.fruit]);f.position.copy(q).multiplyScalar(.9).add(new THREE.Vector3((r()-.5)*.12,-.05,(r()-.5)*.12));f.scale.setScalar(sizes[t.name]||1);group.add(f)}}group.position.set(t.x,0,t.z);tag(group,{title:t.name,body:`${p.ever?'常緑樹':'落葉樹'}｜${state.season}｜${state.growthYear}年後`,meta:[['固定座標',`x ${t.x} / z ${t.z}`],['基準樹高',`${t.h}m`],['基準樹冠半径',`${t.r}m`],['性質',p.ever?'常緑':'落葉']]});return group}
g.isEvergreenSpecies=name=>!!PROFILES[name]?.ever;
})(window);
